### ISSUE TITLE
Make an OPAM package for paco

### ISSUE THREAD

**Issue by jeehoonkang** [snu-sf/paco#1]

**Comment by liyishuai** [comment]
I am maintaining an [OPAM package](https://github.com/coq/opam-coq-archive/tree/master/released/packages/coq-paco) for paco, which is based on [coq-contribs](https://github.com/coq-contribs/paco). I saw that Professor Hur has joined SNU. Shall we switch the OPAM package to use this repository?

**Comment by jeehoonkang** [comment]
Thank you for contacting us!  It would be convenience for us.  I'm updating the repo occasionally.  Every time I do it, I'll let you know by making a comment on this issue.

**Comment by jeehoonkang** [comment]
@minkiminki is this issue resolved?

**Comment by liyishuai** [comment]
I think it's resolved in coq/opam-coq-archive#260.

**Comment by minkiminki** [comment]
@jeehoonkang Yes. It's resolved. Now, you can install paco with following commands.

(for the latest release)
opam repo add coq-released https://coq.inria.fr/opam/released
opam install coq-paco.1.2.8

(for the master branch of this repository)
opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
opam install coq-paco.dev

**Comment by jeehoonkang** [comment]
@liyishuai @minkiminki thanks!  If there're any remaining problems, please feel free to reopen this issue.
