### ISSUE TITLE
Question about respectful functions

### ISSUE THREAD

**Issue by Lysxia** [snu-sf/paco#20]
The new tactics `pupto_init` and `pupto_final` allow us to go back and forth between `paco bot gf` and `paco bot (gf o gres gf)`. Is there ever a reason to stay in `paco bot gf`? Would it be reasonable to make `paco bot (gf o gres gf)` the default way for users of paco to define greatest fixpoints in the first place?

**Comment by jeehoonkang** [comment]
Hi, @Lysxia!

Would you please discuss respectful functors in #19?  The design of #19 is not at all final, and your opinion will be very helpful in revising the PR.  Instead, I will close this issue.

PS.  I think your opinion seems reasonable, but not sure whether it will work (i.e. not breaking anything else).  I would like either you or @minkiminki to further explore the design :)
