### ISSUE TITLE
-Q instead of -R

### ISSUE THREAD

**Issue by andrew-appel** [snu-sf/paco#24]
It would be ideal if Paco could be built with '-Q . Paco"  instead of "-R . Paco". 
To do this would not be difficult, it takes 5 minutes to change every Require statement to use the fully qualified name, Paco.foo instead of foo.

Then, when I include Paco in other developments such as VST, I can write "-Q paco/src Paco" instead of "-R paco/src Paco", where I am using the git submodule "paco".  (One could also do this via opam, but I like to have the option to build VST without opam.)  I want to use -Q so that Paco does not accidentally shadow things in the VST namespace.

You might argue, "But you can already do  "-Q paco/src Paco" to compile clients of Paco, even Paco is internally built with -R."   This is mostly true, but for simplicity in my Makefile I would like to have just one global _CoqProject with just a single entry for Paco, and that entry should be -Q so that Paco does not accidentally overshadow things in the namespace.

It's easy to make this change in the Paco sources, and none of the existing clients of Paco will be broken by this.

**Comment by minkiminki** [comment]
Is it ok with the current version (https://github.com/snu-sf/paco/commit/cb08c1f872d625c32709ac3ba20e97f27ba9d005)?
@andrew-appel

**Comment by andrew-appel** [comment]
Perfect, thank you.
