### ISSUE TITLE
Wrong import in documentation

### ISSUE THREAD

**Issue by cipher1024** [snu-sf/paco#32]
At the top of http://plv.mpi-sws.org/paco/tutorial.html, `Require Import paco.` is written but `Require Import Paco.paco.` is required (with Coq 8.9).

**Comment by minkiminki** [comment]
That tutorial is outdated. You can find the up to date version at [src/tutorial.v](https://github.com/snu-sf/paco/blob/master/src/tutorial.v). (link fixed)

**Comment by cipher1024** [comment]
The link seems broken. Also, it might be good to put the link in the README file.

**Comment by minkiminki** [comment]
Actually, there is already a [link](https://github.com/snu-sf/paco/blob/master/README.md#examples) in the README. :)

**Comment by cipher1024** [comment]
Somehow, I hadn't seen it. I don't remember where I got the link to the wrong doc
