### ISSUE TITLE
pcofix works while gcofix doesn't?

### ISSUE THREAD

**Issue by alxest** [snu-sf/paco#37]
In the example below, `pcofix` tactic works while `gcofix` doesn't.
```
Require Import Coq.Relations.Relation_Definitions.
From Paco Require Import paco.
Let __add_constraint__: relation (rel2 unit (fun _ => unit)) := bot2.
Variable f: (forall R, relation R -> Prop) -> (forall R, relation R -> Prop).
Goal forall R (RR: relation R), (paco2 f bot2 R RR). Proof. pcofix CIH. Abort.
Goal forall R (RR: relation R), (gpaco2 f (cpn2 f) bot2 bot2 R RR). Proof. Fail gcofix CIH. Abort.
```
It seems like `gcofix` is somewhat universe-sensitive while `pcofix` isn't.
Related issue: https://github.com/DeepSpec/InteractionTrees/issues/193

**Comment by gilhur** [comment]
I just checked it.
It is a simple bug of gcofix.
I will fix it soon.

**Comment by gilhur** [comment]
I pushed the fix for this bug.
@minkiminki, can you update the opam package?

**Comment by alxest** [comment]
Thanks for your effort!
