### ISSUE TITLE
gcofix failing in 4.1

### ISSUE THREAD

**Issue by YaZko** [snu-sf/paco#41]
Hello, 

The latest release of gpaco broke a script in Vellvm. It appears to be a side effect to the "fix" in `gcofix` from issue #37, but I haven't looked close enough to figure out what is happening exactly.

The proof failing is the following (it is in the Vellvm repo, but is a purely itree-based thing, it only depends on `Utils/NoEvents.v` ): https://github.com/vellvm/vellvm/blob/master/src/coq/Utils/Commutation.v#L36

We get `Error: Proof is not complete.` when calling `ecofix CIH` where it used to work on the previous version. Unfolding the definition of `ecofix`, it happens when calling `paco_post2 CIH with gL.`.

Am I missing a reason for which it indeed should fail, or did the fix from #37 introduce another bug by side effect?

Best,
Yannick

**Comment by minkiminki** [comment]
I made a hotfix (5a38bcf). Could you test that this patch works? @YaZko

**Comment by YaZko** [comment]
Hello @minkiminki ,

I just tried the patch, it indeed solves the problem perfectly! Thanks a lot.

**Comment by minkiminki** [comment]
Good! I released 4.1.1 and wait for it to be merged in opam-coq-archive.
