### ISSUE TITLE
Add paco to Coq CI

### ISSUE THREAD

**Issue by Lysxia** [snu-sf/paco#45]
The Coq team strongly encourages Coq projects to be added to Coq CI. This allows changes in Coq that break your library to be detected as they happen, so Coq developers may proactively submit pull requests to patch your library. The process is documented here: https://github.com/coq/coq/blob/master/dev/ci/README-users.md

Adding paco to Coq CI would then enable adding itree to Coq CI as well.

**Comment by minkiminki** [comment]
Thanks for letting me know. I will try.

**Comment by minkiminki** [comment]
Added in https://github.com/coq/coq/pull/15551

**Comment by Lysxia** [comment]
Thanks!
