### ISSUE TITLE
Notation 추가

### ISSUE THREAD

**Issue by alxest** [snu-sf/paco#7]
아래 Notation 들을 정의해서 쓰고 있는데 paconotation 에 넣는건 어떨까요?
```
top2 = (fun _ _ => True)
~2 p = (fun x0 x1 => ~ (p x0 x1))
p /2\ q = (fun x0 x1 => p x0 x1 /\ q x0 x1)
```

**Comment by jeehoonkang** [comment]
@alxest This is now a public repo, so I think it'd be better to report bugs in English.  Thanks!
